# SPDX-FileCopyrightText: 2022 Sam Nystrom <sam@samnystrom.dev>
# SPDX-License-Identifier: CC0-1.0

name: Cachix

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - name: Cachix
        uses: cachix/cachix-action@v12
        with:
          name: stonks3141
          extraPullNames: "nix-community"
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: nix build -L --no-link .#nixosConfigurations.pavilion.config.system.build.toplevel
      - run: nix eval --json ".#nixosConfigurations.pavilion.config.system.build.toplevel.outPath" | sed 's/"\(.*\)"/\1/' | cachix push stonks3141
